/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Kzo' at '17/08/05 23:51' with Gradle 3.0
 *
 * @author Kzo, @date 17/08/05 23:51
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
